#!/bin/bash

source ~/Packages/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Shut off annoying message
typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

