#!/bin/bash

# My scripts
export MY_SCRIPTS_DIR="${HOME}/scripts"

# My dotfiles package
export DOTFILES_PACKAGE_DIR="${HOME}/Projects/dotfiles"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Yarn
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
