#!/bin/bash 

# Usefull aliases as shortcuts
alias bckt='git checkout -b '
alias cat='bat'
alias cb='cargo build'
alias cd_dotfiles='cd ${DOTFILES_PACKAGE_DIR}'
alias cd_scripts='cd ${MY_SCRIPTS_DIR}'
alias ckt='git checkout '
alias clr='clear'
alias cmt='git commit -m'
alias cn='cargo new'
alias cr='cargo run'
alias delorean_dark='qdbus org.kde.konsole-$(pgrep konsole) /Sessions/1 setProfile DeloreanDark'
alias delorean_light='qdbus org.kde.konsole-$(pgrep konsole) /Sessions/1 setProfile DeloreanLight'
alias dff='git diff'
alias dotfiles='cd ${DOTFILES_PACKAGE_DIR} && nvim'
alias gadd='git add'
alias lg='git log'
alias ls='exa'
alias nv='nvim'
alias nv_config='cd ${HOME}/.config/nvim && nvim'
alias nv_zsh='cd ${HOME}/zshrc && nvim'
alias p3='python3'
alias pll='git pull'
alias psh='git push'
alias show_aliases='cat ${HOME}/.zsh_config/aliases/Config'
alias source_zsh_updates="source ${MY_SCRIPTS_DIR}/zsh_updates.sh"
alias source_nvchad_updates="source ${MY_SCRIPTS_DIR}/nvchad_updates.sh"
alias source_scripts_updates="source ${MY_SCRIPTS_DIR}/scripts_updates.sh"
alias source_tmux_updates="source ${MY_SCRIPTS_DIR}/tmux_updates.sh"
alias source_zsh='source ${HOME}/.zshrc'
alias sts='git status'
alias tst="cd ${HOME}/Sandboxes"
alias tmux_cheat_sheet='cat ${DOTFILES_PACKAGE_DIR}/tmux/.tmux.cheat_sheet'
alias wk='cd ${HOME}/Projects'
