#!/bin/bash 

# Usefull aliases as shortcuts
alias armv='sudo apt autoremove'
alias bckt='git checkout -b '
alias cd.='code .'
alias cd_dotfiles='cd ${DOTFILES_PACKAGE_DIR}'
alias cd_scripts='cd ${MY_SCRIPTS_DIR}'
alias ckt='git checkout '
alias cmt='git commit -m'
alias dff='git diff'
alias gadd='git add'
alias gupd='sudo apt-get update'
alias gupg='sudo apt-get upgrade'
alias lg='git log'
alias linup='sudo apt-get update && sudo apt-get upgrade -y'
alias nv='nvim'
alias nv_config='nvim ~/.config/nvim'
alias nv_zsh='nvim ~/zshrc/*'
alias p3='python3'
alias pll='git pull'
alias psh='git push'
alias pyts='cd ~/Documents/sandboxes/Python'
alias rsts='cd ~/Documents/sandboxes/Rust'
alias source_zsh_updates="source ${MY_SCRIPTS_DIR}/zsh_updates.sh"
alias source_nvchad_updates="source ${MY_SCRIPTS_DIR}/nvchad_updates.sh"
alias source_scripts_updates="source ${MY_SCRIPTS_DIR}/scripts_updates.sh"
alias source_zsh='source ~/.zshrc'
alias sts='git status'
alias upd='sudo apt update'
alias upg='sudo apt upgrade'
alias vim_zsh='vim ~/.zshrc'
alias xclp='xclip -sel clip'
